### ISSUE TITLE
tsk

### ISSUE THREAD

**Issue by StoneCypher** [gcolbourn/PTTI#2]
You were never cussed at, Greg.  

This is exactly what I said you would do.  You said "of course I won't block you if you don't cuss!"

And then when you needed to, you just pretended.

Exactly as predicted.  Exactly as you promised you wouldn't.

![image](https://github.com/gcolbourn/PTTI/assets/77482/dbc020a8-b677-491a-8e65-c513955a033f)

**Comment by StoneCypher** [comment]
unless "harry potter fanfic" is cussing now i guess 😂

**Comment by StoneCypher** [comment]
oh my, you came back to keep arguing, without removing the mute

how interesting :)

**Comment by StoneCypher** [comment]
Ah, boops, you lied and blocked again.  😂

This time you're pretending I didn't engage with your arguments, while I'm in the process of engaging with a specific one with the wheat thresher, and when I went through every single argument in your essay in the thread that you requested and refused to read.

Instead, you lied and said you wanted to hear such arguments, and then immediately blocked me so that I couldn't answer 😂

But *you're the one who's supposed to give the arguments to support your position*

You're the one who believes that magical AI can somehow destroy the world

I kept asking you how, and ... and you asked me how back, when my answer kept being "it can't" 😭

C'mon, man.

![image](https://github.com/gcolbourn/PTTI/assets/77482/7ac2b837-6814-4a0d-a3f3-d4c69fdec6dc)

# There is no science without honesty.

Good luck to you in raising a hundred thousand dollars from gullible people to "try to stop this" (translation: play Halls of Torment with Dorito fingers then say "oops guess big ai was too powerful, sorry guys, thanks for the half million")

**Comment by StoneCypher** [comment]
You even admitted that I never swore at you, but you didn't apologize for the lie

And that's unfortunate, because it might have made you feel bad enough to not lie this second time, and keep pretending I somehow didn't engage, and keep warbling about "meta level" 🤣

There, there

Roko's Basilisk is not coming to get you, Greg

There, there

**Comment by StoneCypher** [comment]
There is no movement with world renowned scientists, Greg.  You're just some guy on Twitter.  You are not arm in arm with whoever you want to name from the news.

**Comment by StoneCypher** [comment]
"I'd want to hear the thresher argument!"

Well, I want to hear your AGI argument, but it turns out you don't have one

That's okay.  You can block everyone who just asks you to explain your own claims.  That's not a warning sign at all.  You're probably on solid ground.

**Comment by stur86** [comment]
Just going to say that as a completely unrelated developer on this repository I received the notification, wondered what it was about, and got more than I bargained for.

Regardless of your beef, coming to throw a tantrum in some unrelated repository's issue tracker is Not Cool, man. Keep your Twitter spats on Twitter. This is not the place. Closing down.

**Comment by StoneCypher** [comment]
You guys are asking for millions of dollars from vulnerable and terrified individuals so that you can, *somehow*, police Microsoft and Google

But what's not cool is that someone opened a ticket documenting your behavior when someone takes up your bet about disproving you

This is pretty obvious huckster behavior, buddy

**Comment by stur86** [comment]
Sir, this is a ~~Wendy's~~ repository about epidemiology simulations. It has nothing to do with AI.
